### ISSUE TITLE
Popup dialogues (images, settings menus) don't open.

### ISSUE THREAD

**Issue by 343N** [danbovey/Mess#10]
Pop-up dialogues, including the settings icon, the buttons in the chat input box, images, don't work.

**Comment by danbovey** [comment]
For English (US), the only difference is `"Active contacts"` becomes `"Active Contacts"`. Language support was created in #3, so we can add the strings Messenger call that feature for every locale. I'm also now comparing the strings in lower case. It was blocking the rendering of the settings menu, and inside the active contacts area is the user's avatar, so it fixes #9 as well.

Will publish on the Chrome store now.
