### ISSUE TITLE
Display your own name on top of IRC-style messages

### ISSUE THREAD

**Issue by Hammad369** [danbovey/Mess#15]
Is there a way you can have your own name over your messages like discord does? I know it isnt too big of an issue but it will look really good :)

**Comment by danbovey** [comment]
I'd never noticed that before! I'm sure it's possible. Haven't been developing this recently but the next time I look at this I'll make sure this is top of the list.

**Comment by shrx** [comment]
Own name is not displayed currently. Probably due to a change in element class names.
